### ISSUE TITLE
Plugin version 2.3 and missing dependencies

### ISSUE THREAD

**Issue by ctmay4** [bmuschko/gradle-nexus-plugin#49] opened 2015-03-11 19:33 UTC
I just tried updating the plugin from version 2.1.1 to 2.3.  The 2.3 version created a pom.xml without any dependencies.  When I downgraded back to 2.1.1 the dependencies worked again.  

Did something else change in 2.3?

Here is my build.gradle:

```groovy
import org.gradle.internal.jvm.Jvm

plugins {
    id 'java'
    id 'checkstyle'
    id 'findbugs'
    id 'com.bmuschko.nexus' version '2.3'
}

group = 'com.imsweb'
version = '1.0-SNAPSHOT'
description = 'Java client library for staging calculations'

println "Starting build using ${Jvm.current()}"

// UTF-8 for all compilation tasks
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.fasterxml.jackson.core:jackson-core:2.4.4'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.4.4'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.4.4'

    // morphia annotations are needed to make it easier to use in SEER*API
    compile 'org.mongodb.morphia:morphia:0.108'

    compile 'com.google.guava:guava:18.0'

    testCompile 'junit:junit:4.11'
    testCompile 'org.unitils:unitils-core:3.4'
    testCompile 'us.monoid.web:resty:0.3.2'
}

jar {
    manifest {
        attributes('Implementation-Title': project.name,
                'Implementation-Version': version,
                'Implementation-Vendor': group,
                'Created-By': System.properties['java.vm.version'] + ' (' + System.properties['java.vm.vendor'] + ')',
                'Built-By': System.getProperty('user.name'),
                'Built-Date': new Date(),
                'Built-JDK': System.getProperty('java.version'),
        )
    }
}

checkstyle {
    ignoreFailures = true
    configFile = file('config/checkstyle/checkstyle.xml')
}

findbugs {
    toolVersion = '2.0.1'
    ignoreFailures = true
    effort = 'max'
    excludeFilter = file('config/findbugs/findbugs-exclude.xml')
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}

// run the full CS integration test suite
task csIntegrationTest(type: JavaExec) {
    main = 'com.imsweb.staging.cs.CsIntegrationTest'
    classpath = sourceSets.test.runtimeClasspath
}

modifyPom {
    project {
        name 'Staging Java Client'
        description 'A cancer staging client library'
        url 'https://github.com/imsweb/staging-client-java'
        inceptionYear '2015'

        scm {
            url 'https://github.com/imsweb/staging-client-java'
            connection 'scm:https://github.com/imsweb/staging-client-java.git'
            developerConnection 'scm:git@github.com:imsweb/staging-client-java.git'
        }

        licenses {
            license {
                name 'A modified BSD License (BSD)'
                url 'https://github.com/imsweb/staging-client-java/blob/master/LICENSE'
                distribution 'repo'
            }
        }

        developers {
            developer {
                id 'ctmay4'
                name 'Chuck May'
                email 'mayc@imsweb.com'
            }
            developer {
                id 'depryf'
                name 'Fabian Depry'
                email 'depryf@imsweb.com'
            }
        }
    }
}
```

**Comment by bmuschko** [comment] 2015-03-14 13:37
When you are referring to version numbers in your description I am not sure whether you mean Gradle or the plugin. Can you please fix the description?

**Comment by ctmay4** [comment] 2015-03-14 14:25
Sorry.  I was referencing to the plugin version.  I updated the subject.

**Comment by bmuschko** [comment] 2015-03-14 20:53
Do you observe this behavior only when you upload your artifact(s) or also when installing them?

**Comment by ctmay4** [comment] 2015-03-15 12:45
I observed this when uploading a Snapshot build and noticing that the dependency section was missing from the Pom.xml.  Switching to the older version of the plugin fixed the issue.

**Comment by bmuschko** [comment] 2015-03-15 13:13
I added a test case but can't seem to be able to reproduce your issue. You might want to strip down your code to get to the core of the problem.

**Comment by ctmay4** [comment] 2015-03-15 13:37
Strange.  I will try it again next week and verify I can still reproduce.  Thanks for looking into this.

**Comment by ctmay4** [comment] 2015-03-16 21:09
I re-tested and got the same results.  I created a Gist with my results.

https://gist.github.com/ctmay4/720705403a97b425284e

The first file is the build.gradle with the 2.1.1 version of the plugin.  The second file is the resulting pom.xml which was uploaded to the SNAPSHOT server.  It looks perfect.

I then changed the plugin version to 2.3 and re-uploaded.  The third file in the gist is the resulting pom.xml which does not include any of the dependencies.

Not the only thing I changed between the first and second uploads was the plugin version.

**Comment by bmuschko** [comment] 2015-03-16 21:27
At the moment I don't know what the issue is. Could you work on a simple example project that reproduces the issue?

**Comment by ctmay4** [comment] 2015-03-17 17:35
I started fresh and was able to reproduce.  Here is the build.gradle:

```gradle
plugins {
    id 'java'
    id 'com.bmuschko.nexus' version '2.3'
}

group = 'com.imsweb'
version = '1.1-SNAPSHOT'
description = 'Testing nexus plugin dependencies'

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.fasterxml.jackson.core:jackson-core:2.4.4'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.4.4'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.4.4'

    testCompile 'junit:junit:4.11'
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}
```

If I set the plugin version to 2.1.1, then I get this pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.imsweb</groupId>
  <artifactId>gradle-sample</artifactId>
  <version>1.1-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>2.4.4</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.4.4</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.4.4</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

Notice there are dependencies listed.  When I set the plugin version to 2.3, then I get this pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.imsweb</groupId>
  <artifactId>gradle-sample</artifactId>
  <version>1.1-SNAPSHOT</version>
</project>
```

There are no longer dependencies.

I think that is as simple an example as I can think of.  Do you need me to create a Github project or is this enough?

**Comment by bmuschko** [comment] 2015-03-21 17:56
I pushed a fix. That should do it.

**Closed by bmuschko** 2015-03-21 17:56 UTC
Labels: Bug

**Comment by ctmay4** [comment] 2015-03-23 13:14
Just tested and this fixes the issue.  Thanks.
