### ISSUE TITLE
Gradle 4.10.1 breaks modifyPom

### ISSUE THREAD

**Issue by crysxd** [bmuschko/gradle-nexus-plugin#71] opened 2018-11-07 12:24 UTC
We are using this plugin to upload our artifacts to Nexus and encoutered a strange behaviour using gradle 4.10.1. `modifyPom` seems to be ignored using this gradle version. Our configuration:

### gradlew.bat
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.0'
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.bmuschko:gradle-nexus-plugin:2.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

### awesomelib/build.gradle

```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-android'
apply plugin: 'com.bmuschko.nexus'

project.ext.versionName = '2.0.1'
project.ext.versionCode = 101
project.version = project.ext.versionName


android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 28
        versionCode project.ext.versionCode
        versionName project.ext.versionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        resourcePrefix "tracking"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

task makeSnapshot {
    group 'Upload tasks'
    description 'Converts last build into a snapshot'
}

makeSnapshot.doFirst {
    project.version = project.version + "-SNAPSHOT"
    println "Make to Snapshot"
}

task uploadSnapshotArchives {
    group 'Upload tasks'
    description 'Converts last build into a snapshot'
}

uploadSnapshotArchives.dependsOn(makeSnapshot)
uploadSnapshotArchives.dependsOn(uploadArchives)

modifyPom {
    project {
        groupId 'de.awesomecorp.it'
        artifactId 'android-awesomelib'
    }
}

nexus {
    sign = false
    repositoryUrl = 'https://bin.awesomecorp.de/repository/android-internal/'
    snapshotRepositoryUrl = 'https://bin.awesomecorp.de/repository/android-internal-snapshots/'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
}
```
With following `gradle/wrapper/gradle-wrapper.properties`, the artifacts show up on nexus with the path `de.awesomecorp.it:android-awesomelib:2.0.1`:

```
#Wed Nov 07 10:33:26 CET 2018
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
```

If the `gradle/wrapper/gradle-wrapper.properties` file is changed as following, the artifacts show up in nexus as `foldername:awesomelib:2.0.1`:

```
#Wed Nov 07 10:33:26 CET 2018
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
```

This means the `modifyPom` seams to be ignored when using gradle 4.10.1. With gradle 4.6, it is processed as expected. We use `./gradlew :awesomelib:uploadSnapshotArchives` and `./gradlew :awesomelib:uploadArchives` to upload archives to Nexus.

**Comment by bmuschko** [comment] 2018-11-07 16:12
Hi Christian,

It's possible that an update of the Groovy library within Gradle led to a different behavior. It could possibly also be the result of a change to evaluation ordering. This plugin had to use `afterEvaluate` which is not great and can sometimes lead to undesirable behavior.

At the moment I don't have the time to debug the issue. It would be highly appreciated if you could dig into the issue and potentially send a PR. I also wanted to mention that the "old" Maven plugin used in the Nexus plugin has been deprecated more or less. Going forward, Gradle suggests to use the Maven Publish plugin. Optimally, the Nexus plugin would be ported to the Maven Publish plugin. Again, a contribution from the community would be highly appreciated.

**Comment by Burdu** [comment] 2018-11-12 00:15
It doesn't seem to work with gradle 4.6 either on my Android project. `modifyPom` is ignored

**Comment by bmuschko** [comment] 2018-11-13 16:46
I just upgraded this plugin to use Gradle 4.10.2 and my tests that use `modifyPom` do not fail. Could you please provide a _minimal_, executable example that reproduces the issue as a GitHub repo (optimally without the use of the Android plugin)?

**Comment by bmuschko** [comment] 2019-03-05 22:05
I am going to close this issue as I couldn't reproduce it. Please reopen if you are still facing a problem.

**Closed by bmuschko** 2019-03-05 22:05 UTC
Labels: Bug
